
name: Core
main: Kad\XOHRCore\Main
version: 2.1.4
api: 3.0.0
author: Jes'kad Ad'aryc#3845
commands:
  gmc:
    description: Changes your gamemode to Creative
    permission: xohrcore.gmc.use
  gms:
    description: Changes your gamemode to Survival
    permission: xohrcore.gms.use
  gma:
    description: Changes your gamemode to Adventure
    permission: xohrcore.gma.use
  gmspc:
    description: Changes your gamemode to Spectator
    permission: xohrcore.gmspc.use
  day:
    description: Changes the time to Day in the world your in
    permission: xohrcore.day.use
  night:
    description: Changes the time to Night in the world your in
    permission: xohrcore.night.use
  hub:
    description: Teleports you to the Hub
    aliases: ["lobby","spawn"]
  rules:
    description: Shows the servers Rules
  nv:
    description: Gives you NightVision

permissions:
  xohrcore.gmc.use:
    description: GMC Command
    default: OP
  xohrcore.gms.use:
    description: GMS Command
    default: OP
  xohrcore.gma.use:
    description: GMA Command
    default: OP
  xohrcore.gmspc.use:
    description: GMSPC Command
    default: OP
  xohrcore.day.use:
    description: DAY Command
    default: OP
  xohrcore.night.use:
    description: NIGHT Command
    default: OP



