name: Core
main: Kad\XOHRCore\Main
version: 2.0.0
api: 3.0.0
author: Jes'kad Ad'aryc#3845
commands:
  gmc:
    description: Changes your gamemode to Creative
    permission: orioncore.gmc.use
  gms:
    description: Changes your gamemode to Survival
    permission: orioncore.gms.use
  gma:
    description: Changes your gamemode to Adventure
    permission: orioncore.gma.use
  gmspc:
    description: Changes your gamemode to Spectator
    permission: orioncore.gmspc.use
  day:
    description: Changes the time to Day in the world your in
    permission: orioncore.day.use
  night:
    description: Changes the time to Night in the world your in
    permission: orioncore.night.use
  hub:
    description: Teleports you to the Hub
    aliases: ["lobby","spawn"]
  rules:
    description: Shows the servers Rules
  info:
    description: Shows the servers Information

permissions:
  xohrcore.gmc.use:
    description: GMC Command
    default: OP
  xohrcore.gms.use:
    description: GMS Command
    default: OP
  xohrcore.gma.use:
    description: GMA Command
    default: OP
  xohrcore.gmspc.use:
    description: GMSPC Command
    default: OP
  xohrcore.day.use:
    description: DAY Command
    default: OP
  xohrcore.night.use:
    description: NIGHT Command
    default: OP
  rank.vip:
    description: Allows VIP features
    default: OP
  rank.op:
    description: Allows OP Join Features
    default: OP
  hybrid.member:
    description: A command for the mighty, rifting to the HyHub is crucial for our escapades
    default: false
