name: MGCore
main: Clik\MGCore\Main
version: 0.1.0
api: 3.0.0
author: Jes'kad Ad'aryc#3845
commands:
  gmc:
    description: Changes your gamemode to Creative
    permission: orioncore.gmc.use
  gms:
    description: Changes your gamemode to Survival
    permission: orioncore.gms.use
  gma:
    description: Changes your gamemode to Adventure
    permission: orioncore.gma.use
  gmspc:
    description: Changes your gamemode to Spectator
    permission: orioncore.gmspc.use
  day:
    description: Changes the time to Day in the world your in
    permission: orioncore.day.use
  night:
    description: Changes the time to Night in the world your in
    permission: orioncore.night.use
  hub:
    description: Teleports you to the Hub
    aliases: ["lobby","spawn"]
  info:
    description: Shows the servers Info
  rules:
    description: Shows the servers Rules

permissions:
  orioncore.gmc.use:
    description: GMC Command
    default: OP
  orioncore.gms.use:
    description: GMS Command
    default: OP
  orioncore.gma.use:
    description: GMA Command
    default: OP
  orioncore.gmspc.use:
    description: GMSPC Command
    default: OP
  orioncore.day.use:
    description: DAY Command
    default: OP
  orioncore.night.use:
    description: NIGHT Command
    default: OP

